---
title       : My first Slidify
subtitle    : 
author      : Santiago Andrés Rodríguez Arturo  
job         : 
framework   : io2012        # {io2012, html5slides, shower, dzslides, ...}
highlighter : highlight.js  # {highlight.js, prettify, highlight}
hitheme     : tomorrow      # 
widgets     : []            # {mathjax, quiz, bootstrap}
mode        : selfcontained # {standalone, draft}
knit        : slidify::knit2slides
---

## Tabla construida con lenguaje de marcadores 
Librerias necesarias 
```{r, echo=FALSE, message=FALSE}
library(knitr)
library(kableExtra)
library(ggplot2)

```
Creación de la tabla
```{r}
data("mtcars")
kable(head(mtcars,5))

```

---
## Gráfica o imagen estática  
```{r, simple-plot, fig.height = 6, fig.align = 'center', message = F}
require(ggplot2)
qplot(wt, mpg, data = mtcars)
```
 --- #montreal bg:url(http://goo.gl/cF6W2)

 ## Montreal by Night Time

 --- #dillinger

 <iframe src = 'http://dillinger.io' height='600px'></iframe>

 --- .middle 

 Slidify is Awesome
